import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());

app.get('/', (req, res) => res.send('Node.js Backend says Hello! Generated by Backlist.'));

// INJECT:ROUTES

const PORT = process.env.PORT || 8000;
app.listen(PORT, () => console.log(`⚡️ Server running on http://localhost:${PORT}`));