import express, { Express, Request, Response } from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app: Express = express(); // Added :Express type

app.use(cors());
app.use(express.json());

app.get('/', (req: Request, res: Response) => { // Added :Request and :Response types
  res.send('Node.js Backend says Hello! Generated by Backlist.');
});

// INJECT:ROUTES

const PORT: number | string = process.env.PORT || 8000; // Added type for PORT

app.listen(PORT, () => {
  console.log(`⚡️ Server running on http://localhost:${PORT}`);
});