const chalk = require('chalk');
const { execa } = require('execa');
const fs = require('fs-extra');
const path = require('path');
const axios = require('axios'); // For making HTTP requests
const unzipper = require('unzipper'); // For extracting .zip files
const { analyzeFrontend } = require('../analyzer');
const { renderAndWrite, getTemplatePath } = require('./template');

async function generateJavaProject(options) {
  const { projectDir, projectName, frontendSrcDir } = options;
  const group = 'com.backlist.generated'; // A default Java group ID

  try {
    // --- Step 1: Download Base Project from Spring Initializr ---
    console.log(chalk.blue('  -> Contacting Spring Initializr to download a base Spring Boot project...'));
    
    // Define standard dependencies for a web API
    const dependencies = 'web,data-jpa,lombok,postgresql'; // Using PostgreSQL as an example DB driver
    const springInitializrUrl = `https://start.spring.io/starter.zip?type=maven-project&language=java&bootVersion=3.2.0&groupId=${group}&artifactId=${projectName}&name=${projectName}&dependencies=${dependencies}`;

    const response = await axios({
      url: springInitializrUrl,
      method: 'GET',
      responseType: 'stream'
    });

    // --- Step 2: Unzip the Downloaded Project ---
    console.log(chalk.blue('  -> Unzipping the Spring Boot project...'));
    await new Promise((resolve, reject) => {
      const stream = response.data.pipe(unzipper.Extract({ path: projectDir }));
      stream.on('finish', () => {
        console.log(chalk.gray('    -> Project unzipped successfully.'));
        resolve();
      });
      stream.on('error', reject);
    });

    // --- Step 3: Analyze Frontend ---
    const endpoints = await analyzeFrontend(frontendSrcDir);
    const modelsToGenerate = new Map();
    endpoints.forEach(ep => {
      if (ep.schemaFields && ep.controllerName !== 'Default' && !modelsToGenerate.has(ep.controllerName)) {
        modelsToGenerate.set(ep.controllerName, { name: ep.controllerName, fields: Object.entries(ep.schemaFields).map(([key, type]) => ({ name: key, type })) });
      }
    });

    // --- Step 4: Generate Java Entities and Controllers ---
    if (modelsToGenerate.size > 0) {
      console.log(chalk.blue('  -> Generating Java entities and controllers...'));
      
      const javaSrcPath = path.join(projectDir, 'src', 'main', 'java', ...group.split('.'), projectName);
      const entityDir = path.join(javaSrcPath, 'model');
      const controllerDir = path.join(javaSrcPath, 'controller');
      await fs.ensureDir(entityDir);
      await fs.ensureDir(controllerDir);

      for (const [modelName, modelData] of modelsToGenerate.entries()) {
        await renderAndWrite(
          getTemplatePath('java-spring/partials/Entity.java.ejs'),
          path.join(entityDir, `${modelName}.java`),
          { group, projectName, modelName, model: modelData }
        );
        await renderAndWrite(
          getTemplatePath('java-spring/partials/Controller.java.ejs'),
          path.join(controllerDir, `${modelName}Controller.java`),
          { group, projectName, controllerName: modelName }
        );
      }
    }

    // --- Step 5: Configure application.properties ---
    console.log(chalk.blue('  -> Configuring database in application.properties...'));
    const propsPath = path.join(projectDir, 'src', 'main', 'resources', 'application.properties');
    const dbProps = [
      `\n\n# --- Auto-generated by create-backlist ---`,
      `# --- Database Configuration (PostgreSQL) ---`,
      `spring.datasource.url=jdbc:postgresql://localhost:5432/${projectName}`,
      `spring.datasource.username=postgres`,
      `spring.datasource.password=password`,
      `spring.jpa.hibernate.ddl-auto=update`,
      `spring.jpa.show-sql=true`,
    ];
    await fs.appendFile(propsPath, dbProps.join('\n'));
    
    console.log(chalk.green('  -> Java (Spring Boot) backend generation is complete!'));
    console.log(chalk.yellow('\nTo run your new Java backend:'));
    console.log(chalk.cyan('  1. Open the project in a Java IDE (like IntelliJ IDEA or VS Code).'));
    console.log(chalk.cyan('  2. Run the main application file.'));


  } catch (error) {
    if (error.response) {
      throw new Error(`Failed to download from Spring Initializr. Status: ${error.response.status}`);
    }
    throw error;
  }
}

module.exports = { generateJavaProject };